### ISSUE TITLE
Integrate orbit library

### ISSUE THREAD

**Issue by vinzdeb** [jlengrand/ShowMeYourBigSatellite#1]

**Comment by jlengrand** [comment]
What does it mean exactly @vinzdeb ? 
I guess you want to show the satellite orbit. But where do you get it from ? 
And do you already have an idea how you would want to display it ?

**Comment by vinzdeb** [comment]
Ok in my mind it was just to make the first step with the library: retrieve the position of the satellite and provide to client... Which is done now.
My bad, I did not fill the description...
So I close this one and open a new one for "drawing the orbit on the map".

**Comment by jlengrand** [comment]
perfect!
